### ISSUE TITLE
How to run the project

### ISSUE THREAD

**Issue by sailor88128** [Sharad24/Neural-Voice-Cloning-with-Few-Samples#17]
Hi Sharad,
I'm really interested in your project and have cloned it. I'm a little confused about how to use your trained model. It seems train_whole.py is the main code of train. How about utilizing the model? Will you put a readme file then?

**Comment by Sharad24** [comment]
Yes there will be a readme file describing how to utilise the project.

Checkout the comments in this commit to know where we've reached in the implementation as of today: https://github.com/Sharad24/Neural-Voice-Cloning-with-Few-Samples/commit/fc29b952b3c0fb2d54b72bd6f6a437131e9addbc

**Comment by farooqrasheed123** [comment]
how to run the project for our own voice ? The commands given in README are to be typed in python or Anaconda command prompt or in Anaconda console ? Please guide me how to do this ?
