### ISSUE TITLE
Typo Error

### ISSUE THREAD

**Issue by gtmdotme** [Sharad24/Neural-Voice-Cloning-with-Few-Samples#2]
https://github.com/Sharad24/Neural-Voice-Cloning-with-Few-Samples/blob/b56fbebb79577b75899e9841534e31b123e69e03/SpeechEmbedding.ipynb#L82

I think instead of `x = prehead(x)` it should be `x = self.prehead(x)`
Just a **typo**

Also, I wish to know about your code since I found it very useful in pursuing one of my project.

**Comment by Sharad24** [comment]
Hi Gautam, thanks for the input. Will make sure that I change it. The repository is incomplete right now, but it will be finished in the next 15 days. I'll be glad to help you out, please let me know via an email.

**Comment by gtmdotme** [comment]
May I have your gmail ID or any email?

**Comment by Sharad24** [comment]
You can find it in my bio
